###APOLLO
http://localhost:8080/apl/?requestType=getState

###BITCOIN CASH
http://localhost:8080/bch/mainnet/block/tip

###DASH
http://localhost:8080/dash/sync

###DIGIBYTE
http://localhost:8080/dgb/sync

###DOGECOIN
http://localhost:8080/doge/sync

###GROESTLCOIN
http://localhost:8080/grs/sync

###LITECOIN
http://localhost:8080/ltc/sync