version: '3'
services:
  apl_server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - ${APL_API_PORT}:7876
    volumes: 
      - ${APL_BLOCKCHAIN_PATH}:/data
    networks:
      - apl_network
    restart: always
  
  apl_balancer:
    image: nginx:1.19-alpine
    ports:
      - 80:80
    volumes: 
      - ./templates:/etc/nginx/templates
    restart: always
    environment: 
      - NGINX_HOST=_
      - APL_SERVER=apl_server
      - APL_PORT=7876
    networks: 
      - apl_network

networks:
  apl_network: