version: '3'
services:
  apl_server:
    container_name: ${APL_CONTAINER_NAME}
    build:
      context: ${PWD}/coins/apl/server
      dockerfile: Dockerfile
      args: 
        APL_API_PORT: ${APL_API_PORT}
    ports:
      - ${APL_API_PORT}:${APL_API_PORT}
    volumes: 
      - ${APL_BLOCKCHAIN_PATH}:/data
    networks:
      - apl_network
      - nginx_network
    restart: always

networks:
  apl_network:
  nginx_network: