version: '3'
services:
  apl_server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - ${APL_API_PORT}:7876
    volumes: 
      - ${APL_BLOCKCHAIN_PATH}:/data
    networks:
      - apl_network
      - nginx_network
    restart: always

networks:
  apl_network:
  nginx_network: