version: '3'
services:
  bch_database:
    image: mongo:3.4-jessie
    volumes: 
      - ${BCH_DB_PATH}:/data/db
    restart: always
    networks:
      - bch_network
    
  bch_bitcore:
    build:
      context: ../../bitcore
      dockerfile: Dockerfile
    ports:
      - ${BCH_API_PORT}:3000
    environment:
      - DB_HOST=bch_database
      - CHAIN=BCH
    networks:
      - bch_network
      - nginx_network
    restart: always
    depends_on:
      - bch_node
      - bch_database

  bch_node:
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes: 
      - ${BCH_BLOCKCHAIN_PATH}:/data
    networks:
      - bch_network
    restart: always
    
networks:
  bch_network:
  nginx_network: