version: '3'
services:
  nginx:
    build:
      context: ${PWD}/load-balancer
      dockerfile: Dockerfile
    ports: 
      - 443:443
      - 80:80
    volumes: 
      - ${PWD}/load-balancer/config:/etc/nginx/config
    restart: always