version: '3'
services:
  dgb_insight:
    build:
      context: ./insight
      dockerfile: Dockerfile
    ports:
      - ${DGB_API_PORT}:3000
    networks:
      - dgb_network
    environment: 
      - NODE_ENV=production
      - INSIGHT_PORT=3000
      - INSIGHT_NETWORK=livenet
      - BITCOIND_USER=user
      - BITCOIND_PASS=password
      - INSIGHT_PUBLIC_PATH=public
      - BITCOIND_HOST=dgb_node
      - BITCOIND_P2P_HOST=dgb_node
      - BITCOIND_P2P_PORT=30008
      - BITCOIND_PORT=30009
    depends_on:
      - dgb_node
    env_file: .env
    restart: always

  dgb_node:
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes: 
      - ${DGB_BLOCKCHAIN_PATH}:/data
    networks:
      - dgb_network
    restart: always
    
networks:
  dgb_network: