version: '3'
services:
  dgb_insight:
    build:
      context: ${PWD}/coins/dgb/insight
      dockerfile: Dockerfile
    networks:
      - dgb_network
    environment: 
      - NODE_ENV=production
      - DIGIEXPLORER_PORT=3000
      - DIGIEXPLORER_NETWORK=livenet
      - DIGIBYTED_USER=user
      - DIGIBYTED_PASS=password
      - DIGIEXPLORER_PUBLIC_PATH=public
      - DIGIBYTED_HOST=dgb_node
      - DIGIBYTED_P2P_HOST=dgb_node
      - DIGIBYTED_P2P_PORT=30008
      - DIGIBYTED_PORT=30009
    volumes: 
      - ${DATA_DIR}/dgb:/data
    depends_on:
      - dgb_node
    restart: always

  dgb_node:
    build:
      context: ${PWD}/coins/dgb/node
      dockerfile: Dockerfile
    volumes: 
      - ${DATA_DIR}/dgb/blockchain:/data
    networks:
      - dgb_network
    restart: always
    
  nginx:
    image: nginx:1.19-alpine
    ports:
      - ${NGINX_PORT}:80
    volumes: 
      - ${PWD}/nginx/templates:/etc/nginx/templates
    restart: always
    environment: 
      NGINX_HOST: _
      DGB_LOCATION: |-
        #
        location /dgb/ {
          proxy_pass http://dgb_insight:3000/api/;
        }
    restart: always
    env_file:
      - ${PWD}/.env
    networks: 
      - dgb_network

networks:
  dgb_network: