version: '3'
services:
  doge_insight:
    build:
      context: ${PWD}/coins/doge/insight
      dockerfile: Dockerfile
    environment: 
      - NODE_ENV=production
      - INSIGHT_NETWORK=livenet
      - BITCOIND_USER=user
      - BITCOIND_PASS=password
      - INSIGHT_PUBLIC_PATH=public
      - BITCOIND_HOST=doge_node
      - BITCOIND_P2P_HOST=doge_node
      - BITCOIND_P2P_PORT=30008
      - BITCOIND_PORT=30009
    depends_on:
      - doge_node
    restart: always

  doge_node:
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes: 
      - ${DATA_DIR}/doge/blockchain:/data
    networks:
      - doge_network
    restart: always
    
  nginx:
    image: nginx:1.19-alpine
    ports:
      - ${NGINX_PORT}:80
    volumes: 
      - ${PWD}/nginx/templates:/etc/nginx/templates
    restart: always
    environment: 
      NGINX_HOST: _
      DOGE_LOCATION: |-
        #
        location /doge/ {
          proxy_pass http://doge_insight:3000/api/;
        }
    restart: always
    env_file:
      - ${PWD}/.env
    networks: 
      - doge_network

networks:
  doge_network: