version: '3'
services:
  insight:
    build:
      context: ./insight
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes: 
      - /Users/$USER/Desktop/data/doge/blockchain:/data
    networks:
      - doge_network
    environment: 
      - NODE_ENV=production
      - INSIGHT_NETWORK=livenet
      - BITCOIND_USER=${BITCOIND_USER}
      - BITCOIND_PASS=${BITCOIND_PASS}
      - INSIGHT_PUBLIC_PATH=public
      - BITCOIND_HOST=doge_node
      - BITCOIND_P2P_HOST=doge_node
      - BITCOIND_P2P_PORT=${BITCOIND_P2P_PORT}
      - BITCOIND_PORT=${BITCOIND_PORT}
    depends_on:
      - doge_node
    env_file: .env
    restart: always

  doge_node:
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes: 
      - /Users/$USER/Desktop/data/doge/blockchain:/data
    networks:
      - doge_network
    restart: always
    
networks:
  doge_network: