version: '3'
services:
  doge_insight:
    build:
      context: ./insight
      dockerfile: Dockerfile
    ports:
      - ${DOGE_API_PORT}:3000
    networks:
      - doge_network
    environment: 
      - NODE_ENV=production
      - INSIGHT_NETWORK=livenet
      - BITCOIND_USER=user
      - BITCOIND_PASS=password
      - INSIGHT_PUBLIC_PATH=public
      - BITCOIND_HOST=doge_node
      - BITCOIND_P2P_HOST=doge_node
      - BITCOIND_P2P_PORT=30008
      - BITCOIND_PORT=30009
    depends_on:
      - doge_node
    restart: always

  doge_node:
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes: 
      - ${DOGE_BLOCKCHAIN_PATH}:/data
    networks:
      - doge_network
    restart: always
    
networks:
  doge_network: