version: '3'
services:
  grs_insight:
    build:
      context: ./insight
      dockerfile: Dockerfile
    ports:
      - ${GRS_API_PORT}:3000
    networks:
      - grs_network
    environment: 
      - NODE_ENV=production
      - INSIGHT_NETWORK=testnet
      - BITCOIND_USER=user
      - BITCOIND_PASS=password
      - INSIGHT_PUBLIC_PATH=public
      - BITCOIND_HOST=grs_node
      - BITCOIND_P2P_HOST=grs_node
      - BITCOIND_P2P_PORT=30008
      - BITCOIND_PORT=30009
    depends_on:
      - grs_node
      - nginx_network
    restart: always

  grs_node:
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes: 
      - ${GRS_BLOCKCHAIN_PATH}:/data
    networks:
      - grs_network
    restart: always
    
networks:
  grs_network:
  nginx_network: