version: '3'
services:
  #I don't know why, but insight can't connect to grs node if it's not localhost, so I combined them
  insight_node:
    build:
      context: ${PWD}/coins/grs/insight_node
      dockerfile: Dockerfile
    volumes: 
      - ${DATA_DIR}/grs/blockchain:/data
    networks:
      - grs_network
    environment: 
      - NODE_ENV=production
      - INSIGHT_NETWORK=livenet
      - BITCOIND_USER=user
      - BITCOIND_PASS=password
      - INSIGHT_PUBLIC_PATH=public
      - BITCOIND_HOST=localhost
      - BITCOIND_P2P_HOST=localhost
      - BITCOIND_P2P_PORT=30008
      - BITCOIND_PORT=30009
    restart: always
    
  nginx:
    image: nginx:1.19-alpine
    ports:
      - ${NGINX_PORT}:80
    volumes: 
      - ${PWD}/nginx/templates:/etc/nginx/templates
    restart: always
    environment: 
      NGINX_HOST: _
      GRS_LOCATION: |-
        #
        location /grs/ {
          proxy_pass http://insight_node:3000/api/;
        }
    restart: always
    env_file:
      - ${PWD}/.env
    networks: 
      - grs_network

networks:
  grs_network: