version: '3'
services:
  pricer:
    build:
      context: ${PWD}/pricer
      dockerfile: Dockerfile
    networks:
      - pricer_network
    restart: always
    
  nginx:
    image: nginx:1.19-alpine
    ports:
      - ${NGINX_PORT}:80
    volumes: 
      - ${PWD}/nginx/templates:/etc/nginx/templates
    restart: always
    environment: 
      NGINX_HOST: _
      PRICER_LOCATION: |-
        #
        location /pricer/ {
          proxy_pass http://pricer:3000/;
        }
    restart: always
    env_file:
      - ${PWD}/.env
    networks: 
      - pricer_network
    depends_on: 
      - pricer

networks:
  pricer_network: