version: '3'
services:
  balancer:
    image: nginx:1.19-alpine
    ports:
      - 8080:80
    volumes: 
      - ${PWD}/nginx/templates:/etc/nginx/templates
    restart: always
    environment: 
      - NGINX_HOST=_
    restart: always
    env_file:
      - ${PWD}/.env
    networks: 
      - nginx_network

networks:
  nginx_network:

    
