version: '3'
services:
  balancer:
    image: nginx:1.19-alpine
    ports:
      - 8080:80
    volumes: 
      - ./templates:/etc/nginx/templates
    restart: always
    environment: 
      - NGINX_HOST=_