version: '3'
services:
  litecore:
    build:
      context: ./litecore
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes: 
      - /Users/$USER/Desktop/data/ltc/blockchain:/data
    networks:
      - ltc_network
    environment: 
      - NODE_ENV=production
    restart: always
    
networks:
  ltc_network: